apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: kavita-email
version: 0.0.1
appVersion: "latest"
description: Simple email service for kavita
type: service
deprecated: false
home: https://github.com/onypatrickr/catalog.git
icon: https://truecharts.org/_static/img/appicons/kavita.png
keywords:
  - kavita
  - email
  - kavita-email
sources:
  - https://www.kavitareader.com
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.7
    # condition:
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
