image:
  repository: onypatrickr/kavita-email
  pullPolicy: Always
  tag: latest@sha256:a1645dee6ef19dd4de517b77efcc3c99cb3356173d5c1d61ab481f1ffbd09955

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 5003
        port: 10190
env:
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: 465
  SMTP_USER: "332duparc@gmail.com"
  SMTP_PASS: "kp1t1kp1"
  SEND_ADDR: "noreply@332duparc.com"
  DISP_NAME: "332 Du Parc"