image:
  repository: onypatrickr/kavita-email
  pullPolicy: Always
  tag: latest@sha256:a1645dee6ef19dd4de517b77efcc3c99cb3356173d5c1d61ab481f1ffbd09955

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 5003
        port: 10190
env:
  SMTP_HOST:
  SMTP_PORT:
  SMTP_USER:
  SMTP_PASS:
  SEND_ADDR:
  DISP_NAME: